
detect: detect.cpp InterferenceDetector.h InterferenceDetector.cpp ../MapAddr/AccessInfo.cpp
	g++ detect.cpp InterferenceDetector.cpp ../MapAddr/AccessInfo.cpp -std=c++17 -o detect 

clean:
	rm -f detect 

.PHONY: clean
